# Generated by Django 4.2.30 on 2026-06-29 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needs_password_reset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, default='+91', max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='SkillGapResume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume_pdf', models.FileField(upload_to='skill_gap_resumes/')),
                ('extracted_text', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap_resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillGapAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('job_description', models.TextField()),
                ('ats_score', models.IntegerField(default=0)),
                ('match_score', models.IntegerField(default=0)),
                ('gap_score', models.IntegerField(default=0)),
                ('resume_quality_score', models.IntegerField(default=0)),
                ('open_jobs', models.IntegerField(default=0)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('growth_rate', models.CharField(blank=True, max_length=50)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap_results', to='app.skillgapresume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('MISSING', 'Missing')], max_length=20)),
                ('priority', models.CharField(blank=True, choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20, null=True)),
                ('score', models.IntegerField(default=0)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='app.skillgapanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeQualityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('CLARITY', 'Clarity'), ('IMPACT', 'Impact'), ('STRUCTURE', 'Structure'), ('READABILITY', 'Readability'), ('PROFESSIONALISM', 'Professionalism'), ('ATS_READINESS', 'ATS Readiness')], max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_metrics', to='app.skillgapanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('KEYWORD_DENSITY', 'Keyword Density'), ('FORMATTING', 'Formatting'), ('EXPERIENCE_MATCH', 'Experience Match'), ('SOFT_SKILLS', 'Soft Skills'), ('ATS_COMPATIBILITY', 'ATS Compatibility'), ('RELEVANCE_SCORE', 'Relevance Score')], max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_metrics', to='app.skillgapanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume_type', models.CharField(choices=[('AI_WRITTEN', 'AI Written'), ('HUMAN_WRITTEN', 'Human Written'), ('HYBRID', 'Hybrid')], max_length=20)),
                ('detection_confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('ai_written_probability', models.IntegerField(default=50)),
                ('human_written_probability', models.IntegerField(default=50)),
                ('ai_signals', models.JSONField(blank=True, default=list)),
                ('human_signals', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('red_flags', models.JSONField(blank=True, default=list)),
                ('recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_detections', to='app.skillgapanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_detections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('udemy_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('google_link', models.URLField(blank=True, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_roadmaps', to='app.skillgapanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='JobRoleMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=150)),
                ('match_percentage', models.IntegerField(default=0)),
                ('average_salary', models.CharField(blank=True, max_length=100)),
                ('demand_level', models.CharField(blank=True, max_length=50)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='app.skillgapanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='ImprovementTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('impact_percentage', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_tips', to='app.skillgapanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('HIGH', 'High Impact'), ('MEDIUM', 'Medium Impact'), ('LOW', 'Low Impact')], max_length=20)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_areas', to='app.skillgapanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('xp_points', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AICareerSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('role_name', models.CharField(max_length=150)),
                ('is_matched', models.BooleanField(default=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_suggestions', to='app.skillgapanalysis')),
            ],
        ),
    ]
